# Generated by Django 4.1.5 on 2023-03-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_medication_created_remove_medication_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='treatment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.treatment'),
            preserve_default=False,
        ),
    ]
