# Generated by Django 4.1.5 on 2023-03-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_prescription_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
