# Generated by Django 4.1.5 on 2023-03-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_prescription_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='core.appointment'),
        ),
    ]
